export const post = {
  algorithm: [],
  browser: [
    {
      date: 1652872376408,
      title: '关于DNS',
      link: '/post/browser/about_DNS',
      file: 'about_DNS',
      scope: ['browser'],
      buckets: ['post', 'browser'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1652872376408,
      title: '初探V8垃圾回收',
      link: '/post/browser/v8_garbage_collection',
      file: 'v8_garbage_collection',
      scope: ['browser', 'V8'],
      buckets: ['post', 'browser'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694481,
      title: '比较好理解的浏览器缓存',
      link: '/post/browser/browser_cache',
      file: 'browser_cache',
      scope: ['browser'],
      buckets: ['post', 'browser'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694482,
      title: '危险的target="_blank"',
      link: '/post/browser/problem_of_target_blank.',
      file: 'problem_of_target_blank.',
      scope: ['browser'],
      buckets: ['post', 'browser'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694482,
      title: '简单了解一下Shadow DOM',
      link: '/post/browser/simply_shadow_dom',
      file: 'simply_shadow_dom',
      scope: ['browser'],
      buckets: ['post', 'browser'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    }
  ],
  course: [
    {
      date: 1650466212678,
      title: 'Docker容器统一编排部署',
      link: '/post/course/docker_uniformly_arranged_and_deployed',
      file: 'docker_uniformly_arranged_and_deployed',
      scope: ['Docker'],
      buckets: ['post', 'course'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1651667675800,
      title: 'WinPcap中常用函数',
      link: '/post/course/function_in_winpcap',
      file: 'function_in_winpcap',
      scope: ['WinPcap'],
      buckets: ['post', 'course'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1651841050000,
      title: '使用VScode尝试为C添加额外的库',
      link: '/post/course/add_c_lib_use_vscode',
      file: 'add_c_lib_use_vscode',
      scope: ['tools', 'vscode'],
      buckets: ['post', 'course'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    }
  ],
  learning: [
    {
      date: 1649942694482,
      title: '实现一个具有时效性的LocalStorage',
      link: '/post/learning/implement_localStorage_with_timeliness',
      file: 'implement_localStorage_with_timeliness',
      scope: ['JS'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694483,
      title: 'JS连续赋值执行分析',
      link: '/post/learning/js_continuous_assignment',
      file: 'js_continuous_assignment',
      scope: ['JS'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1650034956594,
      title: '关于NodeJS中的流',
      link: '/post/learning/about_node_stream',
      file: 'about_node_stream',
      scope: ['Node'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694483,
      title: 'Vue3位运算的巧妙之处',
      link: '/post/learning/bit_operation_in_shapeFlags',
      file: 'bit_operation_in_shapeFlags',
      scope: ['Vue'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1650808533377,
      title: 'Canvas从零开始实现2048',
      link: '/post/learning/build_2048/index',
      file: 'index',
      scope: ['browser', 'canvas'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page',
      advanced: true
    },
    {
      date: 1649942694484,
      title: 'Canvas为什么变得这么模糊？',
      link: '/post/learning/why_canvas_blur/index',
      file: 'index',
      scope: ['browser', 'canvas'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page',
      advanced: true
    },
    {
      date: 1649942694484,
      title: '理解一下CommonJS和ES Modules',
      link: '/post/learning/cjs_and_esm',
      file: 'cjs_and_esm',
      scope: ['Node'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694484,
      title: 'TypeScript中的条件分布类型为什么要这么设计？',
      link: '/post/learning/distributive_conditional_type',
      file: 'distributive_conditional_type',
      scope: ['TS'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1653321855437,
      title: '探索分块（chunk）传输',
      link: '/post/learning/download_with_chunks',
      file: 'download_with_chunks',
      scope: ['Node', 'ES6'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694485,
      title: 'interface和type索引签名之问',
      link: '/post/learning/index_signature_of_interface_and_type',
      file: 'index_signature_of_interface_and_type',
      scope: ['TS'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1650208113000,
      title: 'JS的二进制家族',
      link: '/post/learning/js_binary_family/index',
      file: 'index',
      scope: ['JS'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694485,
      title: 'JS中this的绑定',
      link: '/post/learning/js_this_binding',
      file: 'js_this_binding',
      scope: ['JS'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1649942694486,
      title: 'JS排序',
      link: '/post/learning/js_sort',
      file: 'js_sort',
      scope: ['JS', 'algorithm'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    },
    {
      date: 1650601098818,
      title: '简单实现Virtual DOM',
      link: '/post/learning/virtual_dom',
      file: 'virtual_dom',
      scope: ['JS', 'browser'],
      buckets: ['post', 'learning'],
      draft: false,
      visible: true,
      lang: 'zh',
      layout: 'page'
    }
  ]
}
